# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-31 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=20, verbose_name='用户账号')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('uphone', models.CharField(max_length=11, verbose_name='手机号')),
            ],
            options={
                'verbose_name': '所有用户',
                'db_table': 'users',
                'verbose_name_plural': '所有用户',
            },
        ),
    ]
