# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-31 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20180731_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='account',
            new_name='uname',
        ),
    ]
