# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-08 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20180731_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='uemil',
            field=models.EmailField(max_length=254, null=True, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='users',
            name='usex',
            field=models.BooleanField(default=1, verbose_name='性别'),
        ),
    ]
