# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-08 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20180808_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='birthday',
            field=models.DateField(null=True, verbose_name='生日'),
        ),
        migrations.AddField(
            model_name='users',
            name='navplace',
            field=models.CharField(max_length=30, null=True, verbose_name='籍贯'),
        ),
    ]
