# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-09 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20180808_1047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='uemil',
            new_name='uemail',
        ),
    ]
